development:
  adapter: postgresql
  database: connfour_development
  pool: 5
  timeout: 5000
  host: localhost
  user: dario
test:
  adapter: postgresql
  database: conn_four_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: conn_four_production
  pool: 5
  timeout: 5000
